version: '3.7'

services:
  redis:
    image: redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"

  securecardtokenize: 
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"  
    depends_on:
      - redis
    environment:
      NODE_ENV: ${NODE_ENV}
      BASE_PATH: ${BASE_PATH}
      PORT: "${PORT}"
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: "${REDIS_PORT}"
      REDIS_DB: "${REDIS_DB}"
      DATA_SECRET_KEY: ${DATA_SECRET_KEY}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
